### PR TITLE
Completed Bower Support

### PR DESCRIPTION
**Pull request by jherdman**
This includes a bower.json file so as to publish it to the repository

### CODE REVIEW

**Comment by arve0** [comment]
available as bower from v0.2.1

**Comment by jherdman** [comment]
Hi @arve0 ! I wanted to follow up with respect to the bower package. I checked the Bower registry today and I noticed it's not listed yet. Is there anything I can do to help out?

**Comment by arve0** [comment]
Try `bower info markdown-it-attrs` in your console. It should be registered.

**Comment by jherdman** [comment]
Dang! You're right. I guess the website hasn't quite caught up yet. Again, many thanks!

**Pull request merged**
