### PR TITLE
Add CSS Modules support

### PR DESCRIPTION
**Pull request by Narazaka**
```
text {..green} -> <p css-module="green">text</p>
```

This feature can work with [posthtml-css-modules](https://github.com/posthtml/posthtml-css-modules) then we can use CSS Modules enabled markdown.

### CODE REVIEW

**Comment by arve0** [comment]
Hi! Thanks for the contribution. CSS-modules are unknown to me, what is the use case? Is it a spec?

**Comment by Narazaka** [comment]
CSS-Modules are new css architecture.
cf. https://glenmaddern.com/articles/css-modules

CSS Modules mainly solves the problem of having difficult designing in the global namespace only in CSS, although not in JavaScript and other languages.
It is often used with high affinity with React, but it is useful not only for React but also for other componentizable templates.

I think it is common to use markdown as a component of a part of a Web site (the other part is React, jade, etc.). On this case, we would like to use CSS Modules inside of markdown as well as other parts already designed with CSS Modules.

It is conceivable to use the class attribute as it is as a CSS Modules attribute name, but it is often when we want to use a fixed and global class name. For this reason, I thought it appropriate to provide the css-modules attribute for CSS Modules separately from the class attribute.

**Comment by arve0** [comment]
Ok, and .. is kind of standardized?

fre. 15. sep. 2017 kl. 07.49 skrev Narazaka <notifications@github.com>:

**Comment by Narazaka** [comment]
It is not a recommendation of W3C or CSSWG, but it is a specification based on scoped css which is an obsolete working draft.
css pseudo-class :scope https://developer.mozilla.org/ja/docs/Web/CSS/%3Ascope
css modules https://github.com/css-modules/css-modules

**Comment by arve0** [comment]
I think you misunderstood me, I ment the `..`-notation. Is it common? I guess it makes sense, `.` being class.

**Comment by arve0** [comment]
Released in `v1.2.0`

**Comment by Narazaka** [comment]
Oops, sorry. ".." is not a standard form in particular, but I thought that it is an easier to understand way from the class ".".
Thank you.

**Pull request merged**
