### PR TITLE
fix: resolve conflict with markdown-it-katex plugin

### PR DESCRIPTION
**Pull request by yndx-birman**
Related issue https://github.com/waylonflinn/markdown-it-katex/issues/24

### CODE REVIEW

**Comment by arve0** [comment]
Hi 👋 Thank you for the patch 👌 Do you mind adding a test? 😊

**Comment by yndx-birman** [comment]
> Hi 👋 Thank you for the patch 👌 Do you mind adding a test? 😊

Hi 👋  Thank you for replying quickly 👍 I added a test to make sure that the plugin does not parse the latex syntax

**Comment by arve0** [comment]
Thanks, looks good 👍 Will merge when at computer.

**Comment by yndx-birman** [comment]
@arve0 Hi! It's not urgent for me, but I'll leave a comment as a reminder

**Comment by arve0** [comment]
Thanks for the reminder, busy times. Released in [v4.1.0](https://github.com/arve0/markdown-it-attrs/releases/tag/v4.1.0).

**Pull request merged**
